apiVersion: v1
kind: Service
metadata:
  name: fake-news-api-service
spec:
  type: NodePort
  selector:
    app: fake-news-api
  ports:
    - port: 8000        # porta no cluster
      targetPort: 8000   # porta no container
      nodePort: 30007    # porta na sua máquina (precisa ser entre 30000 e 32767)
